version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    container_name: blackjack-test-db
    environment:
      POSTGRES_DB: blackjack_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5436:5432"
    # Use tmpfs for in-memory storage - much faster for tests
    tmpfs:
      - /var/lib/postgresql/data:rw,noexec,nosuid,size=256m
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d blackjack_test"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    command: >
      postgres
      -c max_connections=100
      -c shared_buffers=128MB
      -c effective_cache_size=256MB
      -c maintenance_work_mem=32MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=8MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c work_mem=2MB
      -c min_wal_size=64MB
      -c max_wal_size=256MB
      -c fsync=off
      -c synchronous_commit=off
      -c full_page_writes=off 