version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: blackjack-db
    environment:
      POSTGRES_DB: blackjack
      POSTGRES_USER: blackjack_user
      POSTGRES_PASSWORD: blackjack_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blackjack_user -d blackjack"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    command: >
      postgres
      -c max_connections=100
      -c shared_buffers=128MB
      -c effective_cache_size=256MB
      -c maintenance_work_mem=32MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=8MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c work_mem=2MB
      -c min_wal_size=64MB
      -c max_wal_size=256MB

volumes:
  postgres_data: 